### ISSUE TITLE
Error invalid_grant

### ISSUE THREAD

**Issue by AB1908** [dessalines/reddit-history#11]
I get an error trying to use this. Here's stderr:

```
07:32:09.393 [main] INFO  ROOT - {"error": "invalid_grant"}
Exception in thread "main" java.lang.NullPointerException
        at com.reddit.history.App.getAccessToken(App.java:106)
        at com.reddit.history.App.doMain(App.java:60)
        at com.reddit.history.App.main(App.java:265)
```

**Comment by dessalines** [comment]
I just tested this out, and its working fine.

Make sure you provided the correct client_id and client_secret from those instructions.

```

**Comment by AB1908** [comment]
I did have the correct arguments in place. Does it have something to do with 2FA? I have it turned on.

**Comment by dessalines** [comment]
Its worth a try turning it off. I would think that app passwords would still work, but maybe not.

**Comment by AB1908** [comment]
I happened to find another tool to do the job. I'll only pursue this if you ask, turning 2FA off an on is kind of a hassle.

**Comment by dessalines** [comment]
Ah ok, no probs.
