### ISSUE TITLE
Help with the program

### ISSUE THREAD

**Issue by nauposerver** [dessalines/reddit-history#12]
Can someone guide me how to actually do this process? I have java installed.
I downloaded reddit-history.jar but when I click on the file, it doesn't open.
Help please?

**Comment by dessalines** [comment]
Nothing in the instructions tells you to double click this file. You have to follow the full instructions, and use a command line to run this.

https://github.com/dessalines/reddit-history#installation

**Comment by nauposerver** [comment]
Okay I tried but got stuck again...
Is -user and -username the same reddit username?
![Annotation 2020-04-21 195540](https://user-images.githubusercontent.com/43829348/79897560-31e74180-840a-11ea-9756-96fdc7b39a86.png)
Don't know what I'm doing wrong, instructions are very vague, i'm not a programmer sorry

**Comment by dessalines** [comment]
It looks like you're on windows, and the line delimiters are different from `\`. I can't help you there. You'll have to put everything on one line.

**Comment by nauposerver** [comment]
It worked! Thank you very much!

Just want to ask if there's any way to export upvoted items too or is it not possible?

But thank you again!

**Comment by dessalines** [comment]
No probs! Unfortunately not that I know of.
