### ISSUE TITLE
Windows - "-client_id" and "-client_secret" commands not recognized

### ISSUE THREAD

**Issue by threekeys** [dessalines/reddit-history#3]
I created a "personal use script" on my Reddit account page and copied ID and secret values. I created a folder for reddit-history.jar and opened a new command prompt, then ran the command in the readme with the uppercase strings replaced with my account information. `-client_id` and `-client_secret`are not detected:

```
'-client_id' is not recognized as an internal or external command,
operable program or batch file.
```
```
'-client_secret' is not recognized as an internal or external command,
operable program or batch file.
```

Windows 10 64-bit (10.0.14393), Java 8 (update 121).
reddit-history 0.0.3

**Comment by dessalines** [comment]
Could you copy your whole `java -jar` command(without the passwords obvi), and the results?

**Comment by threekeys** [comment]
`java -jar reddit_history.jar -user account -username account -password 8515144 -client_id 52704517 -client_secret 1515797034 -sort new`

I use same username (my Reddit username) for -user and -username. Password, -client_id and -client_secret are examples.
I simply get `'-client_id'/'-client_secret' is not recognized`... error depending on which one command comes first.

**Comment by dessalines** [comment]
Did you try using quotes around the keys? Sometimes with slashes or ampersands they can get messed up.

**Comment by threekeys** [comment]
Sorry for not responding -- I no longer use Reddit and likely won't create an account for testing. If there was spaces in the commands, that will of course cause issues. You can consider this issues as invalid for now.
