### ISSUE TITLE
link in readme is defunct

### ISSUE THREAD

**Issue by allthemikeysaretaken** [dessalines/reddit-history#7]
In the "Limitations" section of the readme file, the link tagged 'help complain like I did' does not work; it redirects to a 404 error.

**Comment by dessalines** [comment]
Looks like reddit deleted the issue.

Reddit hasn't been open source for years, and they put limits on the amount of comments ppl can scrape using the API. They've refused to do anything about that bc they don't want ppl moving to other platforms.
