### ISSUE TITLE
Can anyone help with this error?

### ISSUE THREAD

**Issue by apcrcom** [dessalines/reddit-history#8]
C:\Users\---\Desktop\reddithistory>java -jar reddit-history.jar -user --- -username --- -password --- -client_id --- -client_secret --- -sort new

10:38:15.070 [main] INFO ROOT - {"access_token": "---", "token_type": "bearer", "expires_in": 3600, "scope": "*"}

10:38:15.100 [main] INFO ROOT - file: C:\Users\---\Desktop\reddithistory\reddit

_history\reddit_---_saved_new.md

Exception in thread "main" java.lang.NullPointerException

at com.reddit.history.App.fetcher(App.java:78)

at com.reddit.history.App.doMain(App.java:63)

at com.reddit.history.App.main(App.java:246)

**Comment by dessalines** [comment]
I'll have to check this after this weekend.

**Comment by apcrcom** [comment]
Cheers. appreciate it

**Comment by dessalines** [comment]
Okay this is good now: https://github.com/dessalines/reddit-history/releases
